### ISSUE TITLE
Update build tools

### ISSUE THREAD

**Issue by plastiv** [umano/AndroidSlidingUpPanel#595]
I have an idea of updating infrustracture tools versions for this project:
- [x] build tools 23.0.2 #593 
- [x] android gradle plugin 1.5.0 #602
- [x] gradle wrapper 2.9 #603
- [x] gradle wrapper 2.11 #668 
- [x] delete unused leftovers from gradle migration #594 
- [x] use native gradle project structure replacing custom sourceSet folders #608 
- [x] add travis configuration to make sure sended PRs compiles at least #669
- [x] compile sdk 23 #601 
- [x] support lib 23.1.1 #601 

These changes are not touching core library functionality but It could be a nice thing to have. If you are interested in them I could send PRs over the weekend.

**Comment by tokudu** [comment]
Sure! Feel free to send over any more PRs. I will test and merge.

**Comment by tokudu** [comment]
All done. Thank you so much for your help!
